export default {
    /************** CENTRO DISTRIBUCION ******************/
    GET_CENTROS_DISTRIBUCION_START: '@ENRUTA:GET_CENTROS_DISTRIBUCION_START',
    GET_CENTROS_DISTRIBUCION_SUCCESS: '@ENRUTA:GET_CENTROS_DISTRIBUCION_SUCCESS',
    GET_CENTROS_DISTRIBUCION_ERROR: '@ENRUTA:GET_CENTROS_DISTRIBUCION_ERROR',

    DELETE_CENTRO_DISTRIBUCION_START: '@ENRUTA:DELETE_CENTRO_DISTRIBUCION_START',
    DELETE_CENTRO_DISTRIBUCION_SUCCESS: '@ENRUTA:DELETE_CENTRO_DISTRIBUCION_SUCCESS',
    DELETE_CENTRO_DISTRIBUCION_ERROR: '@ENRUTA:DELETE_CENTRO_DISTRIBUCION_ERROR',

    CREATE_CENTRO_DISTRIBUCION_START: '@ENRUTA:CREATE_CENTRO_DISTRIBUCION_START',
    CREATE_CENTRO_DISTRIBUCION_SUCCESS: '@ENRUTA:CREATE_CENTRO_DISTRIBUCION_SUCCESS',
    CREATE_CENTRO_DISTRIBUCION_ERROR: '@ENRUTA:CREATE_CENTRO_DISTRIBUCION_ERROR',

    UPDATE_CENTRO_DISTRIBUCION_START: '@ENRUTA:UPDATE_CENTRO_DISTRIBUCION_START',
    UPDATE_CENTRO_DISTRIBUCION_SUCCESS: '@ENRUTA:UPDATE_CENTRO_DISTRIBUCION_SUCCESS',
    UPDATE_CENTRO_DISTRIBUCION_ERROR: '@ENRUTA:UPDATE_CENTRO_DISTRIBUCION_ERROR',

    /************** CLIENTES ******************/
    GET_CLIENTES_START: '@ENRUTA:GET_CLIENTES_START',
    GET_CLIENTES_SUCCESS: '@ENRUTA:GET_CLIENTES_SUCCESS',
    GET_CLIENTES_ERROR: '@ENRUTA:GET_CLIENTES_ERROR',

    DELETE_CLIENTE_START: '@ENRUTA:DELETE_CLIENTE_START',
    DELETE_CLIENTE_SUCCESS: '@ENRUTA:DELETE_CLIENTE_SUCCESS',
    DELETE_CLIENTE_ERROR: '@ENRUTA:DELETE_CLIENTE_ERROR',

    CREATE_CLIENTE_START: '@ENRUTA:CREATE_CLIENTE_START',
    CREATE_CLIENTE_SUCCESS: '@ENRUTA:CREATE_CLIENTE_SUCCESS',
    CREATE_CLIENTE_ERROR: '@ENRUTA:CREATE_CLIENTE_ERROR',

    UPDATE_CLIENTE_START: '@ENRUTA:UPDATE_CLIENTE_START',
    UPDATE_CLIENTE_SUCCESS: '@ENRUTA:UPDATE_CLIENTE_SUCCESS',
    UPDATE_CLIENTE_ERROR: '@ENRUTA:UPDATE_CLIENTE_ERROR',

    /************** RUTA ******************/
    GET_RUTAS_START: '@ENRUTA:GET_RUTAS_START',
    GET_RUTAS_SUCCESS: '@ENRUTA:GET_RUTAS_SUCCESS',
    GET_RUTAS_ERROR: '@ENRUTA:GET_RUTAS_ERROR',

    DELETE_RUTA_START: '@ENRUTA:DELETE_RUTA_START',
    DELETE_RUTA_SUCCESS: '@ENRUTA:DELETE_RUTA_SUCCESS',
    DELETE_RUTA_ERROR: '@ENRUTA:DELETE_RUTA_ERROR',

    CREATE_RUTA_START: '@ENRUTA:CREATE_RUTA_START',
    CREATE_RUTA_SUCCESS: '@ENRUTA:CREATE_RUTA_SUCCESS',
    CREATE_RUTA_ERROR: '@ENRUTA:CREATE_RUTA_ERROR',

    UPDATE_RUTA_START: '@ENRUTA:UPDATE_RUTA_START',
    UPDATE_RUTA_SUCCESS: '@ENRUTA:UPDATE_RUTA_SUCCESS',
    UPDATE_RUTA_ERROR: '@ENRUTA:UPDATE_RUTA_ERROR',

    /************** PRODUCTO ******************/
    GET_PRODUCTOS_START: '@ENRUTA:GET_PRODUCTOS_START',
    GET_PRODUCTOS_SUCCESS: '@ENRUTA:GET_PRODUCTOS_SUCCESS',
    GET_PRODUCTOS_ERROR: '@ENRUTA:GET_PRODUCTOS_ERROR',

    DELETE_PRODUCTO_START: '@ENRUTA:DELETE_PRODUCTO_START',
    DELETE_PRODUCTO_SUCCESS: '@ENRUTA:DELETE_PRODUCTO_SUCCESS',
    DELETE_PRODUCTO_ERROR: '@ENRUTA:DELETE_PRODUCTO_ERROR',

    CREATE_PRODUCTO_START: '@ENRUTA:CREATE_PRODUCTO_START',
    CREATE_PRODUCTO_SUCCESS: '@ENRUTA:CREATE_PRODUCTO_SUCCESS',
    CREATE_PRODUCTO_ERROR: '@ENRUTA:CREATE_PRODUCTO_ERROR',

    VALIDAR_CODIGO_PRODUCTO_START: '@ENRUTA:VALIDAR_CODIGO_PRODUCTO_START',
    VALIDAR_CODIGO_PRODUCTO_SUCCESS: '@ENRUTA:VALIDAR_CODIGO_PRODUCTO_SUCCESS',
    VALIDAR_CODIGO_PRODUCTO_ERROR: '@ENRUTA:VALIDAR_CODIGO_PRODUCTO_ERROR',

    UPDATE_PRODUCTO_START: '@ENRUTA:UPDATE_PRODUCTO_START',
    UPDATE_PRODUCTO_SUCCESS: '@ENRUTA:UPDATE_PRODUCTO_SUCCESS',
    UPDATE_PRODUCTO_ERROR: '@ENRUTA:UPDATE_PRODUCTO_ERROR',

    /************** INVENTARIO ******************/
    GET_INVENTARIO_START: '@ENRUTA:GET_INVENTARIO_START',
    GET_INVENTARIO_SUCCESS: '@ENRUTA:GET_INVENTARIO_SUCCESS',
    GET_INVENTARIO_ERROR: '@ENRUTA:GET_INVENTARIO_ERROR',

    DELETE_INVENTARIO_START: '@ENRUTA:DELETE_INVENTARIO_START',
    DELETE_INVENTARIO_SUCCESS: '@ENRUTA:DELETE_INVENTARIO_SUCCESS',
    DELETE_INVENTARIO_ERROR: '@ENRUTA:DELETE_INVENTARIO_ERROR',

    CREATE_INVENTARIO_START: '@ENRUTA:CREATE_INVENTARIO_START',
    CREATE_INVENTARIO_SUCCESS: '@ENRUTA:CREATE_INVENTARIO_SUCCESS',
    CREATE_INVENTARIO_ERROR: '@ENRUTA:CREATE_INVENTARIO_ERROR',

    VALIDAR_CODIGO_INVENTARIO_START: '@ENRUTA:VALIDAR_CODIGO_INVENTARIO_START',
    VALIDAR_CODIGO_INVENTARIO_SUCCESS: '@ENRUTA:VALIDAR_CODIGO_INVENTARIO_SUCCESS',
    VALIDAR_CODIGO_INVENTARIO_ERROR: '@ENRUTA:VALIDAR_CODIGO_INVENTARIO_ERROR',

    UPDATE_INVENTARIO_START: '@ENRUTA:UPDATE_INVENTARIO_START',
    UPDATE_INVENTARIO_SUCCESS: '@ENRUTA:UPDATE_INVENTARIO_SUCCESS',
    UPDATE_INVENTARIO_ERROR: '@ENRUTA:UPDATE_INVENTARIO_ERROR',

    /************** VISITAS ******************/
    GET_VISITAS_START: '@ENRUTA:GET_VISITAS_START',
    GET_VISITAS_SUCCESS: '@ENRUTA:GET_VISITAS_SUCCESS',
    GET_VISITAS_ERROR: '@ENRUTA:GET_VISITAS_ERROR',

    GET_VISITAS_NOW_START: '@ENRUTA:GET_NOW_VISITAS_START',
    GET_VISITAS_NOW_SUCCESS: '@ENRUTA:GET_NOW_VISITAS_SUCCESS',
    GET_VISITAS_NOW_ERROR: '@ENRUTA:GET_NOW_VISITAS_ERROR',

    DELETE_VISITAS_START: '@ENRUTA:DELETE_VISITAS_START',
    DELETE_VISITAS_SUCCESS: '@ENRUTA:DELETE_VISITAS_SUCCESS',
    DELETE_VISITAS_ERROR: '@ENRUTA:DELETE_VISITAS_ERROR',

    CREATE_VISITAS_START: '@ENRUTA:CREATE_VISITAS_START',
    CREATE_VISITAS_SUCCESS: '@ENRUTA:CREATE_VISITAS_SUCCESS',
    CREATE_VISITAS_ERROR: '@ENRUTA:CREATE_VISITAS_ERROR',

    UPDATE_VISITAS_START: '@ENRUTA:UPDATE_VISITAS_START',
    UPDATE_VISITAS_SUCCESS: '@ENRUTA:UPDATE_VISITAS_SUCCESS',
    UPDATE_VISITAS_ERROR: '@ENRUTA:UPDATE_VISITAS_ERROR',

    /************** CLIENTES ******************/
    GET_PROCESOS_START: '@ENRUTA:GET_PROCESOS_START',
    GET_PROCESOS_SUCCESS: '@ENRUTA:GET_PROCESOS_SUCCESS',
    GET_PROCESOS_ERROR: '@ENRUTA:GET_PROCESOS_ERROR',

    DELETE_PROCESO_START: '@ENRUTA:DELETE_PROCESO_START',
    DELETE_PROCESO_SUCCESS: '@ENRUTA:DELETE_PROCESO_SUCCESS',
    DELETE_PROCESO_ERROR: '@ENRUTA:DELETE_PROCESO_ERROR',

    CREATE_PROCESO_START: '@ENRUTA:CREATE_PROCESO_START',
    CREATE_PROCESO_SUCCESS: '@ENRUTA:CREATE_PROCESO_SUCCESS',
    CREATE_PROCESO_ERROR: '@ENRUTA:CREATE_PROCESO_ERROR',

    UPDATE_PROCESO_START: '@ENRUTA:UPDATE_PROCESO_START',
    UPDATE_PROCESO_SUCCESS: '@ENRUTA:UPDATE_PROCESO_SUCCESS',
    UPDATE_PROCESO_ERROR: '@ENRUTA:UPDATE_PROCESO_ERROR',

    /************** CLIENTES ******************/
    GET_VENTAS_START: '@ENRUTA:GET_VENTAS_START',
    GET_VENTAS_SUCCESS: '@ENRUTA:GET_VENTAS_SUCCESS',
    GET_VENTAS_ERROR: '@ENRUTA:GET_VENTAS_ERROR',

    DELETE_VENTA_START: '@ENRUTA:DELETE_VENTA_START',
    DELETE_VENTA_SUCCESS: '@ENRUTA:DELETE_VENTA_SUCCESS',
    DELETE_VENTA_ERROR: '@ENRUTA:DELETE_VENTA_ERROR',

    CREATE_VENTA_START: '@ENRUTA:CREATE_VENTA_START',
    CREATE_VENTA_SUCCESS: '@ENRUTA:CREATE_VENTA_SUCCESS',
    CREATE_VENTA_ERROR: '@ENRUTA:CREATE_VENTA_ERROR',

    UPDATE_VENTA_START: '@ENRUTA:UPDATE_VENTA_START',
    UPDATE_VENTA_SUCCESS: '@ENRUTA:UPDATE_VENTA_SUCCESS',
    UPDATE_VENTA_ERROR: '@ENRUTA:UPDATE_VENTA_ERROR',
}