export default {
    ABORDO_TITLE: 'A bordo',
    EN_RUTA: 'En ruta',
    GUARDANDO: 'Guardando...',
    LIST_ESTABLISHMENT_TITLE: 'Lista de Establecimientos',
    LISTA_CLIENTES_TITLE: 'Lista de Clientes',
    LISTA_PRODUCTOS_TITLE: 'Lista de Productos',
    LISTA_INVENTARIO_TITLE: 'Inventario',
    LISTA_DETALLE_VENTA_TITLE: 'Lista de Productos',
    LISTA_VISITAS_TITLE: 'Visitas',
    REGISTRO_GUARDADO_TITLE: 'Nuevo registro',
    REGISTRO_ERROR_TITLE: 'Algo salio mal',
    REGISTRO_INVALIDO_TITLE: 'Registro inválido',
    REGISTRO_ACTUALIZADO_TITLE: 'Actualizar registro',
    REGISTRO_ELIMINADO_TITLE: 'Borrar registro',
    REGISTRO_ESCANEADO_TITLE: 'Buscar registro',
    UBICACION_GUARDADO_TITLE: 'Ubicación',
    GALERIA_GUARDADO_TITLE: 'Galeria',
    GEOLOCALIZACION_CLIENTE_TITLE: 'Geolocalización del cliente',
    PERMISOS_ESCRITURA_TITLE: 'Permiso de escritura de almacenamiento externo',
    BTN_CERRAR_LABEL: 'Cerrar',
    BTN_GUARDAR_LABEL: 'Guardar',
    BTN_AGREGAR_LABEL: 'Agregar registro',
    BTN_SELECCIONAR_LABEL: 'Seleccionar',
    BTN_CANCELAR_LABEL: 'Cancelar',
    CLAVE_PRINCIPAL: 'Clave principal',
    CLAVE_SECUNDARIA: 'Clave secundaria',
    PRECIO_LISTA: 'Precio de lista',
    PRECIO_MINIMO: 'Precio minimo',
    BTN_CAMARA: 'Camara del Dispositivo',
    BTN_CLIP: 'Clip',
    AGREGAR_PRODUCTO: 'Agregar Producto',
    ESCANEAR_CODIGO_BARRAS: 'Escanear Código de Barras',
    CONFIRMACION: 'Confirmación',
    VENTA: 'Pago Pedido',
    BTN_CONFIRMAR: 'Confirmar',
    BTN_ACEPTAR: 'Aceptar',
    IMPRIMIR_TICKET: 'Impresión de Ticket',
    AGREGAR_CLIENTE: 'Agregar Cliente',
    ERROR_LABEL: 'Error',
    RECIBO_RECIBIR_PRODUCTO: 'RECIBO DE INVENTARIO',
    NOMBRE_EMPRESA: 'Multipollo',
    DIRECCION_EMPRESA: 'Melchor Ocampo, Fraccionamiento La Salud, Colonia Calvario',
    TELEFONO_EMPRESA: '98273-***11',
    CORREO_EMPRESA: 'multipollo@gmail.com',
}