export default {
    LOGIN: 'Login',
    MAIN_TAB: 'Inicio',
    DIRECTORY_ESTABLISHMENT: 'Directorio',
    AROUND_ESTABLISHMENT: 'Cercanos',
    FAVORIT_ESTABLISHMENT: 'Favoritos',
    ROUTES: 'Rutas',
    TOURISTIC_CENTRES: 'Centros Turísticos',
    INCIDENTS: 'Incidencias',
    GONNA: 'Ir a',
    BUSCLOCK: 'Geolocalización',
    CLIENTE: 'Cliente',
    PRODUCTO: 'Producto',
    RECIBIR_PRODUCTO: 'Recibir Producto',
}